import Head from 'next/head'
import Header from '@/components/header/Header'
import Hero from '@/components/hero/Hero'
import News from '@/components/news/News'
import LiveVideo from '@/components/livevideo/LiveVideo'
import StoreCard from '@/components/storecard/StoreCard'
import Footer from '@/components/footer/Footer'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSearch, faStoreAlt } from '@fortawesome/free-solid-svg-icons'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="font-roboto">
      <Head>
        <title>Web Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://1000logos.net/wp-content/uploads/2021/03/Olympics-logo.png" />
      </Head>
      <Header />

      <Hero />
      <div className="flex items-center justify-center my-20">
        <div className="search flex items-center justify-center lg:w-3/5 w-full border-2 border-gray-400 rounded-md bg-white">
          <input className="w-full p-4 py-3 font-roboto font-light text-sm focus:border-transparent focus:outline-none" placeholder="Search for news, teams, category, etc" />
          <FontAwesomeIcon icon={faSearch} className="w-5 mr-4 text-gray-600" />
        </div>
      </div>

      <div className="container mx-auto px-20 flex flex-col items-center">
        <News />
        <LiveVideo />
        <Link href="/video">
          <button className="w-32 px-4 py-2 text-sm bg-primary opacity-90 font-medium text-white hover:opacity-100 shadow-md rounded-md">More Video</button>
        </Link>
      </div>

      <div className="w-full bg-primary my-20 font-roboto">
        <div className="container mx-auto px-20 flex py-10 justify-between">
          <div className="flex-auto w-1/2 flex items-start flex-col justify-center">
            <p className="text-5xl font-bold text-white uppercase">World's Most Popular Sports</p>
            <p className="text-sm font-light text-white mt-3">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet rhoncus, eget vulputate feugiat fermentum quisque ut sit venenatis. Eget eu, turpis a turpis facilisi ac nisi commodo duis. Vel felis nulla pellentesque sit gravida tellus duis. Aliquam auctor nascetur enim quis eu porttitor fames vitae id.
            </p>
            <button className="px-4 py-2 text-sm bg-subburts opacity-90 font-medium mt-5 text-white hover:opacity-100 shadow-md">Read More</button>
          </div>
          <div className="flex-auto flex justify-end">
            <img src="https://i.postimg.cc/0Q33j5BF/unnamed.png" alt="" srcSet="" />
          </div>
        </div>
      </div>

      <div className="container mx-auto px-20 mt-28">
        <div className="flex items-center">
          <FontAwesomeIcon icon={faStoreAlt} className="w-7 text-black mr-3" />
          <p className="text-3xl font-black w-full"> STORE</p>
        </div>
      </div>
      <div className="w-full mb-5">
        <StoreCard />
      </div>
      <div className="w-full mb-20 flex justify-center">
        <button className="w-32 px-4 py-2 text-sm bg-subburts opacity-90 font-medium mt-5 text-white hover:opacity-100 shadow-md">More Items</button>
      </div>

      <div className="w-full bg-color4 my-20 font-roboto">
        <div className="container mx-auto px-20 flex py-20 justify-center">
          <div className="flex flex-col items-center">
            <p className="text-4xl font-black uppercase text-center">Be the first to know about <br /> Sports news everyday
            </p>
            <p className="text-base font-light mt-7 text-center">
              Get Sports analysis, news and updates right to your inbox! <br /> Sign up here so you don't miss a single newsletter and videos
            </p>
            <div className="flex w-full mt-5 justify-between">
              <input className="w-full p-3 px-10  pl-4 font-roboto font-light text-sm focus:border-transparent focus:outline-none mt-5 shadow-md rounded-md  mr-5" placeholder="Enter your email address" />
              <button className="w-44 text-sm bg-primary opacity-90 font-medium mt-5 text-white hover:opacity-100 shadow-md rounded-md">Subscribe Now</button>
            </div>
          </div>
        </div>
      </div>

      <div>
        <Footer />
      </div>
    </div>
  )
}
